function [System, InitialState] = BuildTOADSystem()
% BUILDTOADSYSTEM Assembles the universal TOAD fluid & thermal system topology.
% Defines standard Nodes, Links, LinkMap, and PortMap for the universal solver.
% Includes all fluid lines, tanks, valves, purges, combustors, and thermal links.

    psi2Pa = 6894.757;
    P_atm  = 101325;

    %% Node Geometric & Baseline Definitions
    TankVolOX = 0.03075;
    TankVolFU = 0.03746;
    StartP_Pa = P_atm;
    TargetUllage = 0.10;

    % Bulk Tank
    V_bulk = 0.30;
    P_bulk0 = 6000 * psi2Pa;
    T_bulk0 = 297.15;
    props_bulk = FluidProperties('Nitrogen', 'From_P_T', P_bulk0, T_bulk0);
    m_bulk0 = props_bulk.rho * V_bulk;
    U_bulk0 = props_bulk.u * m_bulk0;

    State.Nodes.TK_N2_BULK = struct(...
        'ID', 1, 'Name', 'TK_N2_BULK', 'Type', 'Gas', 'Fluid', 'Nitrogen', ...
        'V', V_bulk, 'm', m_bulk0, 'U', U_bulk0, ...
        'u', props_bulk.u, 'rho', props_bulk.rho, ...
        'P', P_bulk0, 'T', T_bulk0, 'h', props_bulk.h, ...
        'gamma', props_bulk.gamma, 'Fixed', false);

    % COPVs
    V_copv = 0.036;
    P_copv0 = 4500 * psi2Pa;
    T_copv0 = 297.15;
    props_copv = FluidProperties('Nitrogen', 'From_P_T', P_copv0, T_copv0);
    m_copv0 = props_copv.rho * V_copv;
    U_copv0 = props_copv.u * m_copv0;

    State.Nodes.TK_N2 = struct(...
        'ID', 2, 'Name', 'TK_N2', 'Type', 'Gas', 'Fluid', 'Nitrogen', ...
        'V', V_copv, 'm', m_copv0, 'U', U_copv0, ...
        'u', props_copv.u, 'rho', props_copv.rho, ...
        'P', P_copv0, 'T', T_copv0, 'h', props_copv.h, ...
        'gamma', props_copv.gamma, 'Fixed', false);

    % 4.5ksi to 550psi reg
    V_inr = 5.0e-4;
    P_inr0 = 550 * psi2Pa;
    T_inr0 = 293.15;
    props_inr = FluidProperties('Nitrogen', 'From_P_T', P_inr0, T_inr0);
    m_inr0 = props_inr.rho * V_inr;
    U_inr0 = props_inr.u * m_inr0;

    State.Nodes.Inter_N2_Reg = struct(...
        'ID', 3, 'Name', 'Inter_N2_Reg', 'Type', 'Gas', 'Fluid', 'Nitrogen', ...
        'V', V_inr, 'm', m_inr0, 'U', U_inr0, ...
        'u', props_inr.u, 'rho', props_inr.rho, ...
        'P', P_inr0, 'T', T_inr0, 'h', props_inr.h, ...
        'gamma', props_inr.gamma, 'Fixed', false);

    % Purge manifold
    V_pm = 3.0e-3;
    P_pm0 = P_atm;
    T_pm0 = 293.15;
    props_pm = FluidProperties('Nitrogen', 'From_P_T', P_pm0, T_pm0);
    m_pm0 = props_pm.rho * V_pm;
    U_pm0 = props_pm.u * m_pm0;

    State.Nodes.Purge_Manifold = struct(...
        'ID', 4, 'Name', 'Purge_Manifold', 'Type', 'Gas', 'Fluid', 'Nitrogen', ...
        'V', V_pm, 'm', m_pm0, 'U', U_pm0, ...
        'u', props_pm.u, 'rho', props_pm.rho, ...
        'P', P_pm0, 'T', T_pm0, 'h', props_pm.h, ...
        'gamma', props_pm.gamma, 'Fixed', false);

    % Press manifold 
    V_pman = 1.0e-3;
    State.Nodes.Press_Manifold = struct(...
        'ID', 5, 'Name', 'Press_Manifold', 'Type', 'Gas', 'Fluid', 'Nitrogen', ...
        'V', V_pman, 'm', props_pm.rho * V_pman, 'U', props_pm.u * props_pm.rho * V_pman, ...
        'u', props_pm.u, 'rho', props_pm.rho, ...
        'P', P_pm0, 'T', T_pm0, 'h', props_pm.h, ...
        'gamma', props_pm.gamma, 'Fixed', false);

    % LOx tank 
    V_ull_ox = TankVolOX * TargetUllage;
    V_liq_ox = TankVolOX * (1.0 - TargetUllage);
    T_lox0   = 90.0;
    props_ox_ull = FluidProperties('Nitrogen', 'From_P_T', StartP_Pa, 293.15);
    m_ull_ox0    = props_ox_ull.rho * V_ull_ox;
    U_ull_ox0    = props_ox_ull.u * m_ull_ox0;

    props_ox_liq = FluidProperties('Oxygen', 'From_P_T', StartP_Pa, T_lox0);
    m_liq_ox0    = props_ox_liq.rho * V_liq_ox;
    U_liq_ox0    = props_ox_liq.u * m_liq_ox0;

    State.Nodes.TK_O2_01 = struct(...
        'ID', 6, 'Name', 'TK_O2_01', 'Type', 'TwoZoneTank', 'Fluid', 'Oxygen', ...
        'V', TankVolOX, 'P', StartP_Pa, 'Fixed', false, ...
        'Ullage', struct('m', m_ull_ox0, 'U', U_ull_ox0, 'V', V_ull_ox, ...
                         'P', StartP_Pa, 'T', 293.15, 'rho', props_ox_ull.rho, ...
                         'u', props_ox_ull.u, 'h', props_ox_ull.h, 'gamma', 1.4), ...
        'Liquid', struct('m', m_liq_ox0, 'U', U_liq_ox0, 'V', V_liq_ox, ...
                         'P', StartP_Pa, 'T', T_lox0, 'rho', props_ox_liq.rho, ...
                         'u', props_ox_liq.u, 'h', props_ox_liq.h, 'gamma', 1.1));

    % Fuel tank 
    V_ull_fu = TankVolFU * TargetUllage;
    V_liq_fu = TankVolFU * (1.0 - TargetUllage);
    T_fu0    = 293.15;
    props_fu_ull = FluidProperties('Nitrogen', 'From_P_T', StartP_Pa, T_fu0);
    m_ull_fu0    = props_fu_ull.rho * V_ull_fu;
    U_ull_fu0    = props_fu_ull.u * m_ull_fu0;

    props_fu_liq = FluidProperties('IPA', 'From_P_T', StartP_Pa, T_fu0);
    m_liq_fu0    = props_fu_liq.rho * V_liq_fu;
    U_liq_fu0    = props_fu_liq.u * m_liq_fu0;

    State.Nodes.TK_FU_01 = struct(...
        'ID', 7, 'Name', 'TK_FU_01', 'Type', 'TwoZoneTank', 'Fluid', 'IPA', ...
        'V', TankVolFU, 'P', StartP_Pa, 'Fixed', false, ...
        'Ullage', struct('m', m_ull_fu0, 'U', U_ull_fu0, 'V', V_ull_fu, ...
                         'P', StartP_Pa, 'T', T_fu0, 'rho', props_fu_ull.rho, ...
                         'u', props_fu_ull.u, 'h', props_fu_ull.h, 'gamma', 1.4), ...
        'Liquid', struct('m', m_liq_fu0, 'U', U_liq_fu0, 'V', V_liq_fu, ...
                         'P', StartP_Pa, 'T', T_fu0, 'rho', props_fu_liq.rho, ...
                         'u', props_fu_liq.u, 'h', props_fu_liq.h, 'gamma', 1.15));

    % Pre lines
    V_pmo = 1e-5;
    m_pmo0 = props_ox_liq.rho * V_pmo;
    State.Nodes.Pre_Main_OX = struct(...
        'ID', 8, 'Name', 'Pre_Main_OX', 'Type', 'Line', 'Fluid', 'Oxygen', ...
        'V', V_pmo, 'm', m_pmo0, 'U', props_ox_liq.u * m_pmo0, ...
        'u', props_ox_liq.u, 'rho', props_ox_liq.rho, ...
        'P', StartP_Pa, 'T', T_lox0, 'h', props_ox_liq.h, ...
        'gamma', 1.1, 'Fixed', false);

    V_pmf = 1e-5;
    m_pmf0 = props_fu_liq.rho * V_pmf;
    State.Nodes.Pre_Main_FU = struct(...
        'ID', 9, 'Name', 'Pre_Main_FU', 'Type', 'Line', 'Fluid', 'IPA', ...
        'V', V_pmf, 'm', m_pmf0, 'U', props_fu_liq.u * m_pmf0, ...
        'u', props_fu_liq.u, 'rho', props_fu_liq.rho, ...
        'P', StartP_Pa, 'T', T_fu0, 'h', props_fu_liq.h, ...
        'gamma', 1.15, 'Fixed', false);

    % Lines 
    lineDefs = {
        10, 'Inter_OX',          1.0e-3, 'Oxygen', props_ox_liq;
        11, 'Inter_FU',          1.0e-3, 'IPA',    props_fu_liq;
        12, 'Post_Throttle_OX',  1.0e-3, 'Oxygen', props_ox_liq;
        13, 'Post_Throttle_FU',  1.0e-3, 'IPA',    props_fu_liq;
        14, 'OX_Manifold',       2.0e-3, 'Oxygen', props_ox_liq;
        15, 'FU_Manifold',       2.0e-3, 'IPA',    props_fu_liq;
    };

    for k = 1:size(lineDefs, 1)
        l_id  = lineDefs{k, 1};
        fName = lineDefs{k, 2};
        vol   = lineDefs{k, 3};
        flName = lineDefs{k, 4};
        l_prop = lineDefs{k, 5};

        m_init = l_prop.rho * vol;
        State.Nodes.(fName) = struct(...
            'ID', l_id, 'Name', fName, 'Type', 'Line', 'Fluid', flName, ...
            'V', vol, 'm', m_init, 'U', l_prop.u * m_init, ...
            'u', l_prop.u, 'rho', l_prop.rho, ...
            'P', StartP_Pa, 'T', l_prop.T, 'h', l_prop.h, ...
            'gamma', l_prop.gamma, 'Fixed', false);
    end

    % SKIPPER
    V_skip = 0.001302;
    props_gas_init = FluidProperties('Nitrogen', 'From_P_T', P_atm, 293.15);
    m_skip0 = props_gas_init.rho * V_skip;
    State.Nodes.SKIPPER = struct(...
        'ID', 16, 'Name', 'SKIPPER', 'Type', 'Combustor', 'Fluid', 'CombustionGas', ...
        'V', V_skip, 'm', m_skip0, 'U', props_gas_init.u * m_skip0, ...
        'u', props_gas_init.u, 'rho', props_gas_init.rho, ...
        'P', P_atm, 'T', 293.15, 'h', props_gas_init.h, ...
        'gamma', 1.21, 'cstar', 1600.0, 'isLit', false, 'Fixed', false);

    % DART
    V_dart = 5.0e-4;
    m_dart0 = props_gas_init.rho * V_dart;
    State.Nodes.DART_Chamber = struct(...
        'ID', 17, 'Name', 'DART_Chamber', 'Type', 'Combustor', 'Fluid', 'CombustionGas', ...
        'V', V_dart, 'm', m_dart0, 'U', props_gas_init.u * m_dart0, ...
        'u', props_gas_init.u, 'rho', props_gas_init.rho, ...
        'P', P_atm, 'T', 293.15, 'h', props_gas_init.h, ...
        'gamma', 1.21, 'cstar', 1600.0, 'isLit', false, 'Fixed', false);

    % Atmosphere
    State.Nodes.Atmosphere = struct(...
        'ID', 18, 'Name', 'Atmosphere', 'Type', 'Boundary', 'Fluid', 'Nitrogen', ...
        'V', 1.0, 'm', 1.18, 'U', 2e5, 'u', 1.7e5, 'rho', 1.18, ...
        'P', P_atm, 'T', 293.15, 'h', 2.8e5, 'gamma', 1.4, 'Fixed', true);

    % Virtual
    State.Nodes.Virtual = struct(...
        'ID', 19, 'Name', 'Virtual', 'Type', 'Boundary', 'Fluid', 'Nitrogen', ...
        'V', 1.0, 'm', 1.0, 'U', 0.0, 'u', 0.0, 'rho', 1.0, ...
        'P', 0.0, 'T', 0.0, 'h', 0.0, 'gamma', 1.4, 'Fixed', true);

    %% 2. Link Definitions (Fluid & Unified Thermal Links)
    Links = struct();

    % 1. REG-873D (Regulator: TK_N2 -> Inter_N2_Reg)
    Links.REG_873D = struct('ID', 1, 'Name', 'REG_873D', 'Type', 'Regulator', ...
        'Up', 'TK_N2', 'Down', 'Inter_N2_Reg', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 0.70, 'Cv', 0.70, 'State', 1.0, ...
        'P_set', 550 * psi2Pa, 'Droop', 30 * psi2Pa, 'SPE', 0.003, 'IsOneWay', true);

    % 2. BV-N2-02 (Main Vehicle N2 Isolation Valve: Inter_N2_Reg -> Purge_Manifold)
    Links.BV_N2_02 = struct('ID', 2, 'Name', 'BV_N2_02', 'Type', 'Throttle', ...
        'Up', 'Inter_N2_Reg', 'Down', 'Purge_Manifold', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 2.0, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.05, 'IsOneWay', false);

    % 3. Press OX Check (Purge_Manifold -> TK_O2_01 Ullage)
    Links.Press_OX = struct('ID', 3, 'Name', 'Press_OX', 'Type', 'Check', ...
        'Up', 'Purge_Manifold', 'Down', 'TK_O2_01', 'UpPort', 'Bulk', 'DownPort', 'Ullage', ...
        'MaxCv', 25.0, 'Cv', 25.0, 'State', 1.0, 'P_crack', 0.0, 'IsOneWay', true);

    % 4. Press FU Check (Purge_Manifold -> TK_FU_01 Ullage)
    Links.Press_FU = struct('ID', 4, 'Name', 'Press_FU', 'Type', 'Check', ...
        'Up', 'Purge_Manifold', 'Down', 'TK_FU_01', 'UpPort', 'Bulk', 'DownPort', 'Ullage', ...
        'MaxCv', 25.0, 'Cv', 25.0, 'State', 1.0, 'P_crack', 0.0, 'IsOneWay', true);

    % 5. OX Line 1 (TK_O2_01 Liquid -> Pre_Main_OX)
    Links.OX_Line_1 = struct('ID', 5, 'Name', 'OX_Line_1', 'Type', 'Pipe', ...
        'Up', 'TK_O2_01', 'Down', 'Pre_Main_OX', 'UpPort', 'Liquid', 'DownPort', 'Bulk', ...
        'A', 5e-4, 'Zeta', 20.0, 'Cv', 0, 'State', 1.0, 'IsOneWay', false);

    % 6. FU Line 1 (TK_FU_01 Liquid -> Pre_Main_FU)
    Links.FU_Line_1 = struct('ID', 6, 'Name', 'FU_Line_1', 'Type', 'Pipe', ...
        'Up', 'TK_FU_01', 'Down', 'Pre_Main_FU', 'UpPort', 'Liquid', 'DownPort', 'Bulk', ...
        'A', 5e-4, 'Zeta', 20.0, 'Cv', 0, 'State', 1.0, 'IsOneWay', false);

    % 7. BV-02-03 (Main OX)
    Links.BV_02_03 = struct('ID', 7, 'Name', 'BV_02_03', 'Type', 'Solenoid', ...
        'Up', 'Pre_Main_OX', 'Down', 'Inter_OX', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 2.9, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.05, 'IsOneWay', false);

    % 8. BV-FU-03 (Main FU)
    Links.BV_FU_03 = struct('ID', 8, 'Name', 'BV_FU_03', 'Type', 'Solenoid', ...
        'Up', 'Pre_Main_FU', 'Down', 'Inter_FU', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 2.9, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.05, 'IsOneWay', false);

    % 9. BV-02-04 (Throttle OX)
    Links.BV_02_04 = struct('ID', 9, 'Name', 'BV_02_04', 'Type', 'Throttle', ...
        'Up', 'Inter_OX', 'Down', 'Post_Throttle_OX', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 1.18, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.07, 'IsOneWay', false);

    % 10. BV-FU-04 (Throttle FU)
    Links.BV_FU_04 = struct('ID', 10, 'Name', 'BV_FU_04', 'Type', 'Throttle', ...
        'Up', 'Inter_FU', 'Down', 'Post_Throttle_FU', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 1.18, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.07, 'IsOneWay', false);

    % 11. OX Inj Line
    Links.OX_Inj_Line = struct('ID', 11, 'Name', 'OX_Inj_Line', 'Type', 'Pipe', ...
        'Up', 'Post_Throttle_OX', 'Down', 'OX_Manifold', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'A', 5e-4, 'Zeta', 20.0, 'Cv', 0, 'State', 1.0, 'IsOneWay', false);

    % 12. FU Inj Line
    Links.FU_Inj_Line = struct('ID', 12, 'Name', 'FU_Inj_Line', 'Type', 'Pipe', ...
        'Up', 'Post_Throttle_FU', 'Down', 'FU_Manifold', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'A', 5e-4, 'Zeta', 20.0, 'Cv', 0, 'State', 1.0, 'IsOneWay', false);

    % 13. Inj OX
    Links.Inj_OX = struct('ID', 13, 'Name', 'Inj_OX', 'Type', 'Orifice', ...
        'Up', 'OX_Manifold', 'Down', 'SKIPPER', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'A', 3.25e-5, 'Cd', 0.45, 'Cv', 0, 'State', 1.0, 'IsOneWay', true);

    % 14. Inj FU
    Links.Inj_FU = struct('ID', 14, 'Name', 'Inj_FU', 'Type', 'Orifice', ...
        'Up', 'FU_Manifold', 'Down', 'SKIPPER', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'A', 3.65e-5, 'Cd', 0.77, 'Cv', 0, 'State', 1.0, 'IsOneWay', true);

    % 15. Nozzle
    Links.Nozzle = struct('ID', 15, 'Name', 'Nozzle', 'Type', 'Orifice', ...
        'Up', 'SKIPPER', 'Down', 'Atmosphere', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'A', 0.00129717, 'Cd', 0.95, 'Cv', 0, 'State', 1.0, 'IsOneWay', true);

    % 16. SV-N2-05 (OX Purge)
    Links.SV_N2_05 = struct('ID', 16, 'Name', 'SV_N2_05', 'Type', 'Solenoid', ...
        'Up', 'Purge_Manifold', 'Down', 'Post_Throttle_OX', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 0.20, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.05, 'IsOneWay', false);

    % 17. SV-N2-06 (FU Purge)
    Links.SV_N2_06 = struct('ID', 17, 'Name', 'SV_N2_06', 'Type', 'Solenoid', ...
        'Up', 'Purge_Manifold', 'Down', 'Post_Throttle_FU', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 0.20, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.05, 'IsOneWay', false);

    % 18. SV-N2-07 (DART Purge)
    Links.SV_N2_07 = struct('ID', 18, 'Name', 'SV_N2_07', 'Type', 'Solenoid', ...
        'Up', 'Purge_Manifold', 'Down', 'DART_Chamber', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 0.10, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.10, 'IsOneWay', false);

    % 19. SV-DART-OX
    Links.SV_DART_OX = struct('ID', 19, 'Name', 'SV_DART_OX', 'Type', 'Solenoid', ...
        'Up', 'Inter_OX', 'Down', 'DART_Chamber', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 0.014, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.04, 'IsOneWay', false);

    % 20. SV-DART-FU
    Links.SV_DART_FU = struct('ID', 20, 'Name', 'SV_DART_FU', 'Type', 'Solenoid', ...
        'Up', 'Inter_FU', 'Down', 'DART_Chamber', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 0.0195, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.04, 'IsOneWay', false);

    % 21. Spark (Signal Link)
    Links.Spark = struct('ID', 21, 'Name', 'Spark', 'Type', 'Signal', ...
        'Up', 'Virtual', 'Down', 'DART_Chamber', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 1.0, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.001, 'IsOneWay', true);

    % 22. DART Nozzle
    Links.DART_Nozzle = struct('ID', 22, 'Name', 'DART_Nozzle', 'Type', 'Orifice', ...
        'Up', 'DART_Chamber', 'Down', 'SKIPPER', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'A', 2.62e-5, 'Cd', 1.0, 'Cv', 0, 'State', 1.0, 'IsOneWay', true);

    % 23. BV-N2-FILL (Ground Bulk N2 Fill Valve)
    Links.BV_N2_FILL = struct('ID', 23, 'Name', 'BV_N2_FILL', 'Type', 'Ball', ...
        'Up', 'TK_N2_BULK', 'Down', 'TK_N2', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 1.5, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.05, 'IsOneWay', false);

    % 24..27. RCS Cold-Gas Thrusters (SV-N2-01 .. SV-N2-04)
    Links.SV_N2_01 = struct('ID', 24, 'Name', 'SV_N2_01', 'Type', 'Solenoid', ...
        'Up', 'Purge_Manifold', 'Down', 'Atmosphere', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 0.20, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.02, 'IsOneWay', true);
    Links.SV_N2_02 = struct('ID', 25, 'Name', 'SV_N2_02', 'Type', 'Solenoid', ...
        'Up', 'Purge_Manifold', 'Down', 'Atmosphere', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 0.20, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.02, 'IsOneWay', true);
    Links.SV_N2_03 = struct('ID', 26, 'Name', 'SV_N2_03', 'Type', 'Solenoid', ...
        'Up', 'Purge_Manifold', 'Down', 'Atmosphere', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 0.20, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.02, 'IsOneWay', true);
    Links.SV_N2_04 = struct('ID', 27, 'Name', 'SV_N2_04', 'Type', 'Solenoid', ...
        'Up', 'Purge_Manifold', 'Down', 'Atmosphere', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 0.20, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.02, 'IsOneWay', true);

    % 28. BV-N2-01: COPV High-Pressure Vent
    Links.BV_N2_01 = struct('ID', 28, 'Name', 'BV_N2_01', 'Type', 'Solenoid', ...
        'Up', 'TK_N2', 'Down', 'Atmosphere', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 0.50, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.05, 'IsOneWay', true);

    % 29. BV-O2-01: LOX Tank Ullage Vent
    Links.BV_O2_01 = struct('ID', 29, 'Name', 'BV_O2_01', 'Type', 'Solenoid', ...
        'Up', 'TK_O2_01', 'Down', 'Atmosphere', 'UpPort', 'Ullage', 'DownPort', 'Bulk', ...
        'MaxCv', 1.00, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.05, 'IsOneWay', true);

    % 30. BV-O2-02: LOX Tank Liquid Drain
    Links.BV_O2_02 = struct('ID', 30, 'Name', 'BV_O2_02', 'Type', 'Solenoid', ...
        'Up', 'TK_O2_01', 'Down', 'Atmosphere', 'UpPort', 'Liquid', 'DownPort', 'Bulk', ...
        'MaxCv', 1.00, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.05, 'IsOneWay', true);

    % 31. BV-FU-01: Fuel Tank Ullage Vent
    Links.BV_FU_01 = struct('ID', 31, 'Name', 'BV_FU_01', 'Type', 'Solenoid', ...
        'Up', 'TK_FU_01', 'Down', 'Atmosphere', 'UpPort', 'Ullage', 'DownPort', 'Bulk', ...
        'MaxCv', 1.00, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.05, 'IsOneWay', true);

    % 32. BV-FU-02: Fuel Tank Liquid Drain
    Links.BV_FU_02 = struct('ID', 32, 'Name', 'BV_FU_02', 'Type', 'Solenoid', ...
        'Up', 'TK_FU_01', 'Down', 'Atmosphere', 'UpPort', 'Liquid', 'DownPort', 'Bulk', ...
        'MaxCv', 1.00, 'Cv', 0.0, 'State', 0.0, 'Tau', 0.05, 'IsOneWay', true);

    %% Thermal Links
    % 33. Regen Cooling (Chamber Wall Heat -> Fuel Manifold)
    Links.Regen_Cooling = struct('ID', 33, 'Name', 'Regen_Cooling', 'Type', 'Thermal', ...
        'Up', 'SKIPPER', 'Down', 'FU_Manifold', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'G', 450.0, 'Cv', 0, 'State', 1.0, 'IsOneWay', false);

    % 34. COPV Ambient Convection (COPV Gas/Wall -> Atmosphere)
    Links.COPV_Ambient = struct('ID', 34, 'Name', 'COPV_Ambient', 'Type', 'Thermal', ...
        'Up', 'TK_N2', 'Down', 'Atmosphere', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'G', 15.0, 'Cv', 0, 'State', 1.0, 'IsOneWay', false);

    % 35. LOX Tank Inleak (Atmosphere -> LOX Tank Liquid)
    Links.LOX_Tank_Inleak = struct('ID', 35, 'Name', 'LOX_Tank_Inleak', 'Type', 'Thermal', ...
        'Up', 'Atmosphere', 'Down', 'TK_O2_01', 'UpPort', 'Bulk', 'DownPort', 'Liquid', ...
        'G', 5.0, 'Cv', 0, 'State', 1.0, 'IsOneWay', false);

    %% 3. Pre-Build Fast Numerical Arrays and Maps
    nodeFieldNames = fieldnames(State.Nodes);
    N_N = numel(nodeFieldNames);
    firstNodeStd = standardizeNode(State.Nodes.(nodeFieldNames{1}));
    NodeArray = repmat(firstNodeStd, N_N, 1);
    for i = 1:N_N
        NodeArray(i) = standardizeNode(State.Nodes.(nodeFieldNames{i}));
        NodeArray(i).ID = i;
    end

    linkFieldNames = fieldnames(Links);
    N_L = numel(linkFieldNames);
    firstLinkStd = standardizeLink(Links.(linkFieldNames{1}));
    LinkArray = repmat(firstLinkStd, N_L, 1);
    LinkMap   = zeros(N_L, 2);
    PortMap   = zeros(N_L, 2);

    for j = 1:N_L
        fn = linkFieldNames{j};
        LinkArray(j) = standardizeLink(Links.(fn));
        LinkArray(j).ID = j;

        u_name = LinkArray(j).Up;
        d_name = LinkArray(j).Down;

        u_id = find(strcmp(nodeFieldNames, u_name), 1);
        d_id = find(strcmp(nodeFieldNames, d_name), 1);

        if isempty(u_id), error('BuildTOADSystem: Unknown node "%s"', u_name); end
        if isempty(d_id), error('BuildTOADSystem: Unknown node "%s"', d_name); end

        LinkMap(j, :) = [u_id, d_id];
        
        u_p = parsePortCode(LinkArray(j).UpPort);
        d_p = parsePortCode(LinkArray(j).DownPort);
        PortMap(j, :) = [u_p, d_p];
    end

    %% 4. Pack System & Initial State
    System.Nodes = State.Nodes;
    System.Links = Links;
    System.NodeArray = NodeArray;
    System.LinkArray = LinkArray;
    System.LinkMap   = LinkMap;
    System.PortMap   = PortMap;
    System.Env       = struct('T_amb', 293.15, 'WindVel', 1.5, 'P_atm', P_atm);

    System.Link.State = struct();
    for j = 1:N_L
        fn = linkFieldNames{j};
        System.Link.State.(fn) = Links.(fn).State;
    end

    State.Time = 0.0;
    State.LinkStates = System.Link.State;
    State.NodeArray  = NodeArray;
    State.LinkArray  = LinkArray;
    InitialState = State;
end

%% --- Helper: Parse Port Code ---
function code = parsePortCode(portStr)
    if isnumeric(portStr)
        code = portStr;
    elseif ischar(portStr) || isstring(portStr)
        pLower = lower(strtrim(portStr));
        if strcmp(pLower, 'ullage') || strcmp(pLower, 'gas') || strcmp(pLower, 'top')
            code = 1;
        elseif strcmp(pLower, 'liquid') || strcmp(pLower, 'bottom')
            code = 2;
        else
            code = 0;
        end
    else
        code = 0;
    end
end

%% --- Helper: Standardize Node to Homogeneous Schema ---
function n_std = standardizeNode(n)
    defZone = struct('m', 0.0, 'U', 0.0, 'V', 0.0, 'P', 0.0, 'T', 293.15, ...
                     'rho', 0.0, 'u', 0.0, 'h', 0.0, 'gamma', 1.4);
    defNode = struct(...
        'ID', 0, 'Name', '', 'Type', 'Gas', 'Fluid', 'Nitrogen', ...
        'V', 1e-3, 'm', 0.0, 'U', 0.0, 'u', 0.0, 'rho', 0.0, ...
        'P', 101325.0, 'T', 293.15, 'h', 0.0, 'gamma', 1.4, ...
        'cstar', 0.0, 'isLit', false, 'Fixed', false, ...
        'SparkActive', false, 'TorchLit', false, ...
        'Ullage', defZone, 'Liquid', defZone);
    n_std = defNode;
    f = fieldnames(n);
    for k = 1:numel(f)
        n_std.(f{k}) = n.(f{k});
    end
end

%% --- Helper: Standardize Link to Homogeneous Schema ---
function l_std = standardizeLink(l)
    defLink = struct(...
        'ID', 0, 'Name', '', 'Type', 'Valve', ...
        'Up', '', 'Down', '', 'UpPort', 'Bulk', 'DownPort', 'Bulk', ...
        'MaxCv', 0.0, 'Cv', 0.0, 'State', 1.0, 'Tau', 0.05, ...
        'A', 0.0, 'Cd', 1.0, 'Zeta', 0.0, ...
        'P_set', 0.0, 'Droop', 0.0, 'SPE', 0.0, 'P_crack', 0.0, ...
        'IsOneWay', false, 'G', 0.0, 'Flow', 0.0, 'IsChoked', false, 'FlowDir', 1.0);
    l_std = defLink;
    f = fieldnames(l);
    for k = 1:numel(f)
        l_std.(f{k}) = l.(f{k});
    end
end
