function FlightDynamicsGen(C)
% Symbolic defiitions
syms r1 r2 r3               % earth frame position (R3 up, NWU frame)
syms v1 v2 v3               % earth frame velocity
syms q0 q1 q2 q3            % earth-body quaternion
syms omega1 omega2 omega3   % earth-body angular velocity
syms m_lox m_ipa            % Propellant masses
syms theta phi;             % thrust angles
syms thrust                 % thrust magnitude
syms roll                   % roll input (Nm)
syms J [3 3]                % Dry Intertia Matrix

% System constants
syms m_dry g rTB            
syms OxMassI  FuMassI      
syms OxHeight FuHeight     
syms OxRadius FuRadius      
syms Ox_Z Fu_Z           
syms MaxThrust MaxMdot OF 

% Monte Carlo Params
syms J_d [3 3]              % Disturbance inertia matrix
syms TB_d [3 1]             % dry CoM disturbance
syms MaxMdot_d              % Drain rate variation

% Total Mass
m = m_dry + m_lox + m_ipa;

%Earth-frame position & velocity
r = [r1; r2; r3];
v = [v1; v2; v3];

%Full quaternion vector
q = [q0; q1; q2; q3];

%DCM's
C_BI = quatRot(q);
C_IB = C_BI.';

%Angular velocities
omegaB = [omega1; omega2; omega3];

%Body frame thrust vector
TB = thrust * [cos(theta)*sin(phi); -sin(theta); cos(theta)*cos(phi)];

%Earth frame net force
FI = C_IB * TB + [0; 0;-m*g];

%Rdot and Vdot
rdot = v;
vdot = FI / m;

% Tank drain dynamics
mdot_lox = -thrust / MaxThrust * OF / (1 + OF) * (MaxMdot + MaxMdot_d);
mdot_ipa = -thrust / MaxThrust * 1 / (1 + OF) * (MaxMdot + MaxMdot_d);

% Propellant Fill height
OxFluidHeight = (m_lox / OxMassI) * OxHeight * 0.9;
FuFluidHeight = (m_ipa / FuMassI) * FuHeight * 0.9;

% Propellant inertias
J_xx = 1/12 * m_lox * (3 * OxRadius^2 + OxFluidHeight^2);
J_zz = 1/2 * m_lox * OxRadius^2;
J_lox = [J_xx, 0, 0;
         0, J_xx, 0;
         0,    0, J_zz];

J_xx = 1/12 * m_ipa * (3 * FuRadius^2 + FuFluidHeight^2);
J_zz = 1/2 * m_ipa * FuRadius^2;
J_ipa = [J_xx, 0, 0;
         0, J_xx, 0;
         0,    0, J_zz];

% Fluid fills & location of CoM
OxFluidLocation = Ox_Z + OxFluidHeight / 2;
FuFluidLocation = Fu_Z + FuFluidHeight / 2;
CGz = (m_dry * rTB + m_lox * OxFluidLocation + m_ipa * FuFluidLocation) / m;

% Distances to CG
d_dry = rTB - CGz + TB_d(3);
d_lox = OxFluidLocation - CGz;
d_ipa = FuFluidLocation - CGz;

% Shifted Inertias
J_dry = J + m_dry * diag([d_dry^2, d_dry^2, 0]);
J_lox = J_lox + m_lox * diag([d_lox^2, d_lox^2, 0]);
J_ipa = J_ipa + m_ipa * diag([d_ipa^2, d_ipa^2, 0]);

% Bring everything to instantaneous CG (w.r.t Engine attachment frame)
J_tot = J_dry + J_lox + J_ipa + J_d;

% Body frame moment (Roll torque along the thrust vector axis due to contra
% EDF) (TODO: UPDATE for use with RCS)
% Off center moments for Simulation
MB = zetaCross([0; 0; -CGz] + TB_d)*TB + (TB * roll) / thrust;

% Dynamics
qdot = 0.5 * HamiltonianProd(q) * [0; omegaB];
netTau = (MB - zetaCross(omegaB) * J_tot * omegaB);

%State vector & disturbance struct
x = [q; r; v; omegaB; m_lox; m_ipa];
u = [theta; phi; thrust; roll];
    
%State derivatives
xdot_6DoF = [qdot; rdot; vdot];
xdot_Mass = [mdot_lox; mdot_ipa];

% Subsitute numeric values of constants into xdot
constVal = [C.m_dry; C.g; C.rTB; C.J(:); C.MaxThrust; C.MaxMdot; C.OF;
            C.OxMass; C.FuMass; C.OxHeight; C.FuHeight; C.OxRadius;
            C.FuRadius; C.Ox_Z; C.Fu_Z];
constVec = [m_dry; g; rTB; J(:); MaxThrust; MaxMdot; OF;
            OxMassI; FuMassI; OxHeight; FuHeight; OxRadius;
            FuRadius; Ox_Z; Fu_Z];
xdot_6DoF = subs(xdot_6DoF, constVec, constVal);
xdot_Mass = subs(xdot_Mass, constVec, constVal);
J_tot = subs(J_tot, constVec, constVal);
netTau = subs(netTau, constVec, constVal);

disp('Generating RawDynamics.m...');
filename = "RawDynamics";
matlabFunction(xdot_6DoF, xdot_Mass, J_tot, netTau, ...
'File', './Flight Dynamics/Dynamics Files/' + filename, 'Vars', {x, u, J_d, TB_d, MaxMdot_d}, ...
'Outputs', {'xdot_kin', 'xdot_mass', 'J_tot', 'netTau'});

% Remove auto-gen header for simpler version control
filePath = fullfile('.', 'Flight Dynamics', 'Dynamics Files', filename + '.m');
lines = readlines(filePath);
isToolboxLine = contains(lines, 'This function was generated by the Symbolic Math Toolbox');
idxToRemove = find(isToolboxLine);
if ~isempty(idxToRemove)
    % Group the toolbox line and the date line
    linesToRemove = [idxToRemove, idxToRemove + 1]; 
    
    % Delete those lines
    lines(linesToRemove) = [];
    
    % Overwrite the file with the clean code
    writelines(lines, filePath);
end
end
