function [Q_cham_loss, Q_fuel_gain, ThermalState_new] = RegenThermalModel(~, P_cham, mdot_fu, ~, ThermalState, dt, OF)
% REGENTHERMALMODEL Regenerative cooling heat exchange and pressure drop for SKIPPER.
% Uses pre-computed 2D lookup tables generated by SKRegen2_ElectricBoogalo.
%
% Inputs:
%   T_cham           - Chamber gas temperature [K]
%   P_cham           - Chamber pressure [Pa]
%   mdot_fu          - Coolant (IPA) mass flow rate [kg/s]
%   T_fu_in          - Inlet coolant temperature [K]
%   ThermalState     - Struct with field .T_wall, .DeltaP, .Qdot
%   dt               - Time step [s]
%   OF               - (Optional) Current mixture ratio (default: 1.2)
%
% Outputs:
%   Q_cham_loss      - Thermal energy removed from chamber gas [J]
%   Q_fuel_gain      - Thermal energy delivered into fuel [J]
%   ThermalState_new - Updated thermal state struct

    if nargin < 7 || isempty(OF), OF = 1.2; end
    if nargin < 5 || isempty(ThermalState)
        ThermalState = struct('T_wall', 293.15, 'DeltaP', 0.0, 'Qdot', 0.0);
    end

    % Quasi-steady steady-state targets from precomputed SKIPPER tables
    [Q_ss, DP_ss, Tw_ss] = RegenHeatTransfer(P_cham, mdot_fu, OF);

    % Physical Wall Thermal Capacitance (m*cp ~ 1150 J/K, tau_th ~ 0.15 s)
    % Physical Liner cannot change temperature or heat flux instantaneously in 5 ms.
    tau_th = 0.15; % seconds
    alpha_th = min(1.0, dt / tau_th);

    T_wall_prev = ThermalState.T_wall;
    T_wall_new  = T_wall_prev + alpha_th * (Tw_ss - T_wall_prev);

    Q_prev = 0.0;
    if isfield(ThermalState, 'Qdot'), Q_prev = ThermalState.Qdot; end
    Q_regen_new = Q_prev + alpha_th * (Q_ss - Q_prev);

    % Physical Coolant Jacket Hydraulic Inertia (80 channels, tau_hyd ~ 0.02 s)
    % Smooths high-frequency acoustic/discrete limit-cycle chatter
    tau_hyd = 0.02; % seconds
    alpha_hyd = min(1.0, dt / tau_hyd);

    DP_prev = 0.0;
    if isfield(ThermalState, 'DeltaP'), DP_prev = ThermalState.DeltaP; end
    DP_regen_new = DP_prev + alpha_hyd * (DP_ss - DP_prev);

    ThermalState_new.T_wall = T_wall_new;
    ThermalState_new.DeltaP = DP_regen_new;
    ThermalState_new.Qdot   = Q_regen_new;

    Q_cham_loss = Q_regen_new * dt; % J
    Q_fuel_gain = Q_regen_new * dt; % J
end
